cmake_minimum_required(VERSION 3.0.2)
project(xgc2_scene_runtime)
find_package(catkin REQUIRED COMPONENTS rospy geometry_msgs std_msgs visualization_msgs tf2_ros xgc2_geometry_msgs)
catkin_python_setup()
catkin_package(CATKIN_DEPENDS rospy geometry_msgs std_msgs visualization_msgs tf2_ros xgc2_geometry_msgs)
catkin_install_python(PROGRAMS scripts/scene_node DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
install(DIRECTORY launch/ DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}/launch)
install(FILES README.md DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})
if(CATKIN_ENABLE_TESTING)
  catkin_add_nosetests(test)
endif()
